### ISSUE TITLE
How to stop reinstalling requirement on every time I reboot sd?

### ISSUE THREAD

**Issue by hypiuser** [Astropulse/sd-palettize#3]
I use the network in China, so I sometimes lose my connection to GitHub,Every time I start, I get a prompt like this:

![Z@T4 1ARSU3CQEASR}T6I 0](https://github.com/Astropulse/sd-palettize/assets/96646880/99a0a8b4-fc24-4697-8e2f-3a9b103b27fa)
This is when I am lucky, and when I am unlucky, I will not be able to install successfully and report a long error.I installed other extensions and only this one has the issue
How should I stop the repeated installation, thank you.

**Comment by Zevgor** [comment]
I also have been seeing this issue

**Comment by thorcx** [comment]
我也遇到此问题了. install.py安装写的有点问题，进入到webui/extensions/sd-palettize/ 目录，找到install.py,修改如下图：
<img width="678" alt="image" src="https://github.com/Astropulse/sd-palettize/assets/4484365/b2be2593-78b6-4a8c-82d6-be3109062dfd">
重新启动就不会每次要求安装依赖了
