### ISSUE TITLE
Installation into WebUI Forge 

### ISSUE THREAD

**Issue by NikitkaPine** [Astropulse/sd-palettize#5]
how do I install Palettize in WebUI Forge? I'm new to working with Stable Diffusion, I use Stability Matrix for this

**Comment by Astropulse** [comment]
This is only made for automatic1111 webui. I'm not sure if extensions for that are compatible with forge, but I have no plans on making a forge-specific version.

**Comment by NikitkaPine** [comment]
I have already figured out how to work with the neural network, and I will say that the Palettize works very stably with Forge version
