### ISSUE TITLE
Use this without automatic?

### ISSUE THREAD

**Issue by korruptcow** [Astropulse/sd-palettize#6]
Wondering is there is a way to use this just to process and image. I had to swap UI's to run a  new model and i always use pattelize to down sample colors.  I just need to run on an image that was already generated.  I am using swarmui at the moment if there is a way to get it working there.

thanks

**Comment by Astropulse** [comment]
I don't plan on making a specific implementation for swarmui. The functions inside the python scripts are very self-contained, so you can just modify the script and call the functions directly instead of hooking into automatic1111's ui layer.

**Comment by korruptcow** [comment]
Thanks.. I got it work on forge :D thanks for explanation i was wondering if you could run it without being inside a UI.
